server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/business/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

upload:
  path: E:\Neuedu\Neusoft Practice\neuedu.idea\picture

alipay:
  callback:
    url: http://4xq7g9.natappfree.cc/order/alipay_callback.do
  qrcode:
    path: E:\Neuedu\Neusoft Practice\neuedu.idea\支付宝模块资源文件\picture\
  public:
    key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi+67aaNkFj3IAx2OjGixLvNPGkuAFg0iZrUTRbGTAvUeENFi5DHAeMN/8g9o7lrsE6A1WvxTwhpkNMhIr+QvHJnL4bwGsD8FSIi8FMSNRpcXgHolzzKab2oo+PqznvYzyBiUQOMSpbh7NGa8zT60iT0uvZXr0ZJPmfXkR01MwbZIxl/JuzhcpEGc/fN6noZoEthUZ/GY1SMuScd0ENSRjlOm2s1DHyv+G31IxSYFartsKD4pikFIpcK/NdkAh0ruh8yomvlDxUQ4kRd8OwLqd7wExEcBn+EpT4Zu5pMc2ozxCqOgOpGoHJY6h35FMntsRP/pQW491uYmg0jERwfErwIDAQAB

